version: '3'
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    container_name: web

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - "TZ=Asia/Tokyo"
    container_name: db
