CREATE TABLE codes (
    code_type  VARCHAR(50)       NOT NULL COMMENT 'コード種別',
    code       TINYINT UNSIGNED  NOT NULL COMMENT 'コード値',
    name       VARCHAR(50)       NOT NULL COMMENT 'コード名称',
    sort_order TINYINT UNSIGNED  NOT NULL DEFAULT 0 COMMENT '表示順',
    PRIMARY KEY (code_type, code),
    INDEX idx_code_type (code_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='コードマスター';

-- 性別
INSERT INTO codes (code_type, code, name, sort_order) VALUES
('gender', 0, '不明', 0),
('gender', 1, '男性', 1),
('gender', 2, '女性', 2),
('gender', 9, 'その他', 3);

-- 都道府県
INSERT INTO codes (code_type, code, name, sort_order) VALUES
('prefecture',  1, '北海道',   1),
('prefecture',  2, '青森県',   2),
('prefecture',  3, '岩手県',   3),
('prefecture',  4, '宮城県',   4),
('prefecture',  5, '秋田県',   5),
('prefecture',  6, '山形県',   6),
('prefecture',  7, '福島県',   7),
('prefecture',  8, '茨城県',   8),
('prefecture',  9, '栃木県',   9),
('prefecture', 10, '群馬県',  10),
('prefecture', 11, '埼玉県',  11),
('prefecture', 12, '千葉県',  12),
('prefecture', 13, '東京都',  13),
('prefecture', 14, '神奈川県', 14),
('prefecture', 15, '新潟県',  15),
('prefecture', 16, '富山県',  16),
('prefecture', 17, '石川県',  17),
('prefecture', 18, '福井県',  18),
('prefecture', 19, '山梨県',  19),
('prefecture', 20, '長野県',  20),
('prefecture', 21, '岐阜県',  21),
('prefecture', 22, '静岡県',  22),
('prefecture', 23, '愛知県',  23),
('prefecture', 24, '三重県',  24),
('prefecture', 25, '滋賀県',  25),
('prefecture', 26, '京都府',  26),
('prefecture', 27, '大阪府',  27),
('prefecture', 28, '兵庫県',  28),
('prefecture', 29, '奈良県',  29),
('prefecture', 30, '和歌山県', 30),
('prefecture', 31, '鳥取県',  31),
('prefecture', 32, '島根県',  32),
('prefecture', 33, '岡山県',  33),
('prefecture', 34, '広島県',  34),
('prefecture', 35, '山口県',  35),
('prefecture', 36, '徳島県',  36),
('prefecture', 37, '香川県',  37),
('prefecture', 38, '愛媛県',  38),
('prefecture', 39, '高知県',  39),
('prefecture', 40, '福岡県',  40),
('prefecture', 41, '佐賀県',  41),
('prefecture', 42, '長崎県',  42),
('prefecture', 43, '熊本県',  43),
('prefecture', 44, '大分県',  44),
('prefecture', 45, '宮崎県',  45),
('prefecture', 46, '鹿児島県', 46),
('prefecture', 47, '沖縄県',  47);
