CREATE TABLE persons (
    id             BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    last_name      VARCHAR(50)      NOT NULL COMMENT '姓',
    first_name     VARCHAR(50)      NOT NULL COMMENT '名',
    last_name_kana VARCHAR(100)     NOT NULL DEFAULT '' COMMENT '姓（カナ）',
    first_name_kana VARCHAR(100)    NOT NULL DEFAULT '' COMMENT '名（カナ）',
    email          VARCHAR(254)     NOT NULL COMMENT 'メールアドレス',
    phone          VARCHAR(20)      NOT NULL DEFAULT '' COMMENT '電話番号',
    birth_date     DATE             NULL     COMMENT '生年月日',
    gender         TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '性別（0:不明 1:男性 2:女性 9:その他）',
    zipcode        CHAR(7)          NOT NULL DEFAULT '' COMMENT '郵便番号（ハイフンなし7桁）',
    prefecture     VARCHAR(10)      NOT NULL DEFAULT '' COMMENT '都道府県',
    city           VARCHAR(50)      NOT NULL DEFAULT '' COMMENT '市区町村',
    address_line   VARCHAR(100)     NOT NULL DEFAULT '' COMMENT '番地・建物名',
    created_at     DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_email (email),
    INDEX idx_last_name_kana (last_name_kana),
    INDEX idx_zipcode (zipcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='個人情報';
